#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven
Version  : 2.2.0
Release  : 2
URL      : https://github.com/apache/maven/archive/maven-2.2.0.tar.gz
Source0  : https://github.com/apache/maven/archive/maven-2.2.0.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.0.5/maven-2.0.5.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.0.6/maven-2.0.6.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.0.7/maven-2.0.7.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.0.8/maven-2.0.8.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.0.9/maven-2.0.9.pom
Source6  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.0/maven-2.0.pom
Source7  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.2.0/maven-2.2.0.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/maven/2.2.1/maven-2.2.1.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/maven/3.0.4/maven-3.0.4.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/maven/3.0/maven-3.0.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/maven/3.6.0/maven-3.6.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-data = %{version}-%{release}

%description
-------------------------------------------------------------------------------
Bootstrapping Maven
-------------------------------------------------------------------------------

%package data
Summary: data components for the mvn-maven package.
Group: Data

%description data
data components for the mvn-maven package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.9
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.2.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.2.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/2.2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/3.0.4
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/3.0.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/3.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/3.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/3.6.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven/3.6.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.5/maven-2.0.5.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.6/maven-2.0.6.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.7/maven-2.0.7.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.8/maven-2.0.8.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.0.9/maven-2.0.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.0/maven-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.2.0/maven-2.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/2.2.1/maven-2.2.1.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/3.0.4/maven-3.0.4.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/3.0/maven-3.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven/3.6.0/maven-3.6.0.pom
